"""widget starter questions (SAN-1096, FR-C8)

Revision ID: 29b8ba503fc2
Revises: 8ab7662fbc0f
Create Date: 2026-10-07 11:16:28.430701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '29b8ba503fc2'
down_revision: Union[str, None] = '8ab7662fbc0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # poc_chunks' removal is pre-existing model/DB drift from app/poc, unrelated
    # to FR-C8 — left alone here; autogenerate only surfaced it because this
    # revision happens to be the next one taken against the dev DB.
    op.add_column('widget_configs', sa.Column('starter_questions_json', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widget_configs', 'starter_questions_json')
    # ### end Alembic commands ###
