"""bots: add crm_webhook_url

Revision ID: 595217e6e1dd
Revises: d9fa4a56172d
Create Date: 2026-10-01 11:02:23.473902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '595217e6e1dd'
down_revision: Union[str, None] = 'd9fa4a56172d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # poc_chunks is the unrelated Phase 0 PoC table living in the same local
    # Postgres instance — autogenerate always proposes dropping it since it
    # isn't declared in models.py. Not part of this migration; left alone.
    op.add_column('bots', sa.Column('crm_webhook_url', sa.String(length=1024), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'crm_webhook_url')
    # ### end Alembic commands ###
