"""avatar fields, super admin flag, plans table

Revision ID: 62912fc75082
Revises: afff71009406
Create Date: 2026-10-01 10:11:25.255470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '62912fc75082'
down_revision: Union[str, None] = 'afff71009406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_text', sa.String(length=100), nullable=False),
    sa.Column('tagline', sa.String(length=255), nullable=False),
    sa.Column('features_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # poc_chunks is the unrelated Phase 0 PoC table living in the same local
    # Postgres instance — autogenerate always proposes dropping it since it
    # isn't declared in models.py. Not part of this migration; left alone,
    # same as afff71009406.
    op.add_column('bots', sa.Column('avatar_id', sa.String(length=32), nullable=False, server_default='orbit'))
    op.add_column('bots', sa.Column('avatar_name', sa.String(length=100), nullable=False, server_default=''))
    op.add_column('users', sa.Column('is_super_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_super_admin')
    op.drop_column('bots', 'avatar_name')
    op.drop_column('bots', 'avatar_id')
    op.drop_table('plans')
    # ### end Alembic commands ###
