"""routing rules, teams, business hours (SAN-1112, FR-H3)

Revision ID: 7225a7ea4764
Revises: e1f2a3b4c5d6
Create Date: 2026-10-07 10:27:42.376716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7225a7ea4764'
down_revision: Union[str, None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('bot_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_bot_id'), 'teams', ['bot_id'], unique=False)
    op.create_index(op.f('ix_teams_tenant_id'), 'teams', ['tenant_id'], unique=False)
    op.create_table('routing_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('bot_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('page_pattern', sa.String(length=1024), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_rules_bot_id'), 'routing_rules', ['bot_id'], unique=False)
    op.create_index(op.f('ix_routing_rules_team_id'), 'routing_rules', ['team_id'], unique=False)
    op.create_index(op.f('ix_routing_rules_tenant_id'), 'routing_rules', ['tenant_id'], unique=False)
    # poc_chunks' removal is pre-existing model/DB drift from app/poc, unrelated
    # to FR-H3 — left alone here; autogenerate only surfaced it because this
    # revision happens to be the next one taken against the dev DB.
    op.add_column('bots', sa.Column('business_hours_json', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('conversations', sa.Column('routed_team_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'conversations', 'teams', ['routed_team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'routed_team_id')
    op.drop_column('bots', 'business_hours_json')
    op.drop_index(op.f('ix_routing_rules_tenant_id'), table_name='routing_rules')
    op.drop_index(op.f('ix_routing_rules_team_id'), table_name='routing_rules')
    op.drop_index(op.f('ix_routing_rules_bot_id'), table_name='routing_rules')
    op.drop_table('routing_rules')
    op.drop_index(op.f('ix_teams_tenant_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_bot_id'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
