"""payments: gateways, billing profile, orders, order sequences

Revision ID: 7cccf59f22fd
Revises: 62912fc75082
Create Date: 2026-10-01 10:31:00.121899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7cccf59f22fd'
down_revision: Union[str, None] = '62912fc75082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_profile',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('supplier_gstin', sa.String(length=32), nullable=False),
    sa.Column('supplier_address', sa.String(length=512), nullable=False),
    sa.Column('supplier_city', sa.String(length=100), nullable=False),
    sa.Column('supplier_state', sa.String(length=100), nullable=False),
    sa.Column('supplier_country', sa.String(length=100), nullable=False),
    sa.Column('supplier_pincode', sa.String(length=16), nullable=False),
    sa.Column('supplier_email', sa.String(length=255), nullable=False),
    sa.Column('supplier_phone', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_gateways',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('test_client_id', sa.String(length=255), nullable=False),
    sa.Column('test_client_secret_enc', sa.Text(), nullable=False),
    sa.Column('live_client_id', sa.String(length=255), nullable=False),
    sa.Column('live_client_secret_enc', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('payment_order_sequences',
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('last_value', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('prefix')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.Column('module_type', sa.String(length=32), nullable=False),
    sa.Column('gateway_code', sa.String(length=32), nullable=False),
    sa.Column('payment_mode', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('gateway_order_id', sa.String(length=255), nullable=False),
    sa.Column('gateway_transaction_id', sa.String(length=255), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_gstin', sa.String(length=32), nullable=False),
    sa.Column('customer_address', sa.String(length=512), nullable=False),
    sa.Column('customer_city', sa.String(length=100), nullable=False),
    sa.Column('customer_state', sa.String(length=100), nullable=False),
    sa.Column('customer_country', sa.String(length=100), nullable=False),
    sa.Column('customer_pincode', sa.String(length=16), nullable=False),
    sa.Column('is_intra_state', sa.Boolean(), nullable=True),
    sa.Column('tax_json', sa.JSON(), nullable=False),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_orders_workspace_id'), 'orders', ['workspace_id'], unique=False)
    # poc_chunks is the unrelated Phase 0 PoC table living in the same local
    # Postgres instance — autogenerate always proposes dropping it since it
    # isn't declared in models.py. Not part of this migration; left alone.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_workspace_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('payment_order_sequences')
    op.drop_table('payment_gateways')
    op.drop_table('billing_profile')
    # ### end Alembic commands ###
