"""notifications: in-app, email, slack (SAN-1113, FR-H4)

Revision ID: 8ab7662fbc0f
Revises: 7225a7ea4764
Create Date: 2026-10-07 10:49:05.805241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ab7662fbc0f'
down_revision: Union[str, None] = '7225a7ea4764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('bot_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_bot_id'), 'notifications', ['bot_id'], unique=False)
    op.create_index(op.f('ix_notifications_conversation_id'), 'notifications', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_workspace_id'), 'notifications', ['workspace_id'], unique=False)
    # poc_chunks' removal is pre-existing model/DB drift from app/poc, unrelated
    # to FR-H4 — left alone here; autogenerate only surfaced it because this
    # revision happens to be the next one taken against the dev DB.
    op.add_column('bots', sa.Column('slack_webhook_url', sa.String(length=1024), nullable=False, server_default=''))
    op.add_column('memberships', sa.Column('email_notifications', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memberships', 'email_notifications')
    op.drop_column('bots', 'slack_webhook_url')
    op.drop_index(op.f('ix_notifications_workspace_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_conversation_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_bot_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
