"""plans: add billable amount/currency

Revision ID: d9fa4a56172d
Revises: 7cccf59f22fd
Create Date: 2026-10-01 10:34:27.356891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd9fa4a56172d'
down_revision: Union[str, None] = '7cccf59f22fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # poc_chunks is the unrelated Phase 0 PoC table living in the same local
    # Postgres instance — autogenerate always proposes dropping it since it
    # isn't declared in models.py. Not part of this migration; left alone.
    op.add_column('plans', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('plans', sa.Column('currency', sa.String(length=8), nullable=False, server_default='INR'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'currency')
    op.drop_column('plans', 'amount')
    # ### end Alembic commands ###
